/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Empresa.vistas;


import Empresa.modelos.Producto;
import Empresa.controladores.ControladorInventario;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;
/**
 *
 * @author diego.cruang
 */
public class ModificarInventarioDialog extends javax.swing.JDialog {

     private JTable tabla;
    private DefaultTableModel modeloTabla;
    private List<Producto> inventarioOriginal;

    public ModificarInventarioDialog(JFrame parent, boolean par) {
        super(parent, "Modificar Inventario", true);
        setSize(800, 400);
        setLocationRelativeTo(parent);
        setLayout(new BorderLayout());

        // Columnas: Código, Nombre, Stock Actual, (+)Ingreso, (-)Merma, Resultado Final
        String[] columnas = {"Código", "Nombre", "Stock Actual", "Ingreso", "Merma", "Nuevo Stock"};
        modeloTabla = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 3 || column == 4; // Solo ingreso y merma editables
            }
        };
        tabla = new JTable(modeloTabla);
        JScrollPane scroll = new JScrollPane(tabla);

        cargarInventario();

        // Botones
        JPanel panelBotones = new JPanel();
        JButton btnDescartar = new JButton("Descartar");
        JButton btnModificar = new JButton("Modificar");

        btnDescartar.addActionListener(e -> dispose());

        btnModificar.addActionListener(e -> {
            aplicarModificaciones();
            JOptionPane.showMessageDialog(this, "✅ Modificaciones realizadas exitosamente.");
            dispose();
        });

        panelBotones.add(btnDescartar);
        panelBotones.add(btnModificar);

        add(scroll, BorderLayout.CENTER);
        add(panelBotones, BorderLayout.SOUTH);

        setVisible(true);
    }

    private void cargarInventario() {
        inventarioOriginal = ControladorInventario.obtenerInventario(); // Este método debe acceder a la BD
        for (Producto p : inventarioOriginal) {
            modeloTabla.addRow(new Object[]{
                    p.getCodigo(),
                    p.getNombre(),
                    p.getCantidad(),
                    0,
                    0,
                    p.getCantidad()
            });
        }

        modeloTabla.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int ingreso = parseEntero(modeloTabla.getValueAt(row, 3));
            int merma = parseEntero(modeloTabla.getValueAt(row, 4));
            int actual = (int) modeloTabla.getValueAt(row, 2);
            modeloTabla.setValueAt(actual + ingreso - merma, row, 5);
        });
    }

    private int parseEntero(Object valor) {
        try {
            return Integer.parseInt(valor.toString());
        } catch (Exception e) {
            return 0;
        }
    }

    private void aplicarModificaciones() {
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            String codigo = modeloTabla.getValueAt(i, 0).toString();
            int nuevoStock = (int) modeloTabla.getValueAt(i, 5);

            ControladorInventario.actualizarStockProducto(codigo, nuevoStock);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarInventarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarInventarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarInventarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarInventarioDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarInventarioDialog dialog = new ModificarInventarioDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
