/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Empresa.vistas;

import Empresa.controladores.EmpleadoDAO;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author diego.cruang
 */
public class PantallaLoginPOS extends javax.swing.JFrame {

    private JTextField txtCodigo;

    public PantallaLoginPOS() {
        setTitle("Acceso POS");
        setSize(300, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        txtCodigo = new JTextField();
        txtCodigo.setEditable(false);
        txtCodigo.setFont(new Font("Arial", Font.BOLD, 24));
        txtCodigo.setHorizontalAlignment(JTextField.CENTER);

        JPanel panelTeclado = new JPanel(new GridLayout(4, 3, 5, 5));
        for (int i = 1; i <= 9; i++) {
            int numero = i;
            JButton btn = new JButton(String.valueOf(i));
            btn.setFont(new Font("Arial", Font.BOLD, 20));
            btn.addActionListener(e -> agregarNumero(numero));
            panelTeclado.add(btn);
        }

        JButton btnBorrar = new JButton("←");
        btnBorrar.setFont(new Font("Arial", Font.BOLD, 20));
        btnBorrar.addActionListener(e -> borrarUltimo());

        JButton btn0 = new JButton("0");
        btn0.setFont(new Font("Arial", Font.BOLD, 20));
        btn0.addActionListener(e -> agregarNumero(0));

        JButton btnEntrar = new JButton("Entrar");
        btnEntrar.setFont(new Font("Arial", Font.BOLD, 18));
        btnEntrar.addActionListener(e -> validarCodigo());

        panelTeclado.add(btnBorrar);
        panelTeclado.add(btn0);
        panelTeclado.add(btnEntrar);

        add(txtCodigo, BorderLayout.NORTH);
        add(panelTeclado, BorderLayout.CENTER);
        setVisible(true);
    }

    private void agregarNumero(int num) {
        txtCodigo.setText(txtCodigo.getText() + num);
    }

    private void borrarUltimo() {
        String texto = txtCodigo.getText();
        if (!texto.isEmpty()) {
            txtCodigo.setText(texto.substring(0, texto.length() - 1));
        }
    }

    private void validarCodigo() {
        String claveIngresada = txtCodigo.getText(); 

        String puesto = EmpleadoDAO.verificarClave(claveIngresada);
        if (puesto == null) {
            JOptionPane.showMessageDialog(null, "Clave incorrecta.");
        } else {
            boolean esAdmin = puesto.equalsIgnoreCase("administrador");
            this.dispose();
            new MenuPOS(esAdmin);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLoginPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLoginPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLoginPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLoginPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLoginPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
